import { Ionicons } from "@expo/vector-icons";
import React, { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useApp } from "@/src/context/AppContext";
import { apiRequest } from "@/src/lib/api";
import { useColors } from "@/src/components/common";

type Message = { role: "user" | "assistant"; content: string };
export default function ChatScreen() {
  const { t, token, language } = useApp(); const c = useColors(); const insets = useSafeAreaInsets();
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: language === "hi" ? "नमस्ते! मैं KrishiAI हूँ। आपकी फसल और खेत के बारे में आज क्या जानना चाहते हैं?" : "Namaste! I’m KrishiAI. What would you like to know about your crop today?" }]);
  const [value, setValue] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const send = async (text = value) => { if (!text.trim() || !token || busy) return; setValue(""); setError(""); const next = [...messages, { role: "user" as const, content: text.trim() }]; setMessages(next); setBusy(true); try { const response = await apiRequest<{ reply: string }>("/ai/chat", { method: "POST", body: JSON.stringify({ message: text.trim(), language }) }, token); setMessages([...next, { role: "assistant", content: response.reply }]); } catch (e) { setError(e instanceof Error ? e.message : "Message could not be sent"); } finally { setBusy(false); } };
  return <KeyboardAvoidingView style={[styles.root, { backgroundColor: c.bg }]} behavior={Platform.OS === "ios" ? "padding" : "height"} keyboardVerticalOffset={Platform.OS === "ios" ? 10 : 0}>
    <View style={[styles.header, { paddingTop: insets.top + 15, borderBottomColor: c.border }]}><View style={[styles.bot, { backgroundColor: c.brand }]}><Ionicons name="leaf" size={23} color="#fff" /></View><View style={{ flex: 1 }}><Text style={[styles.title, { color: c.text }]}>{t.chatTitle}</Text><Text style={[styles.subtitle, { color: c.muted }]}>{t.chatSubtitle}</Text></View><View style={styles.online}><View style={styles.onlineDot} /><Text style={[styles.onlineText, { color: c.muted }]}>AI</Text></View></View>
    <ScrollView contentContainerStyle={styles.messages} showsVerticalScrollIndicator={false}><View style={styles.suggestions}>{t.suggestions.map((suggestion) => <Pressable testID="chat-suggestion" key={suggestion} onPress={() => void send(suggestion)} style={[styles.chip, { backgroundColor: c.card, borderColor: c.border }]}><Text style={[styles.chipText, { color: c.brand }]}>{suggestion}</Text></Pressable>)}</View>{messages.map((message, index) => <View key={`${message.role}-${index}`} style={[styles.bubble, message.role === "user" ? [styles.userBubble, { backgroundColor: c.brand }] : [styles.aiBubble, { backgroundColor: c.card, borderColor: c.border }]]}><Text style={{ color: message.role === "user" ? "#fff" : c.text, lineHeight: 20, fontSize: 14 }}>{message.content}</Text></View>)}{busy && <View testID="chat-loading" style={[styles.typing, { backgroundColor: c.card }]}><ActivityIndicator size="small" color={c.brand} /><Text style={{ color: c.muted, fontSize: 12 }}>KrishiAI is thinking...</Text></View>}{!!error && <Text testID="chat-error" style={[styles.error, { color: c.danger }]}>{error}</Text>}</ScrollView>
    <View style={[styles.composer, { paddingBottom: Math.max(insets.bottom, 10), backgroundColor: c.bg, borderTopColor: c.border }]}><TextInput testID="chat-input" value={value} onChangeText={setValue} onSubmitEditing={() => void send()} returnKeyType="send" placeholder={t.messagePlaceholder} placeholderTextColor={c.muted} style={[styles.input, { backgroundColor: c.card, borderColor: c.border, color: c.text }]} /><Pressable testID="chat-send" accessibilityLabel={t.send} onPress={() => void send()} style={[styles.send, { backgroundColor: c.brand }, !value.trim() && { opacity: .45 }]}><Ionicons name="arrow-up" size={21} color="#fff" /></Pressable></View>
  </KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, header: { paddingHorizontal: 18, paddingBottom: 15, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", gap: 11 }, bot: { width: 47, height: 47, borderRadius: 16, alignItems: "center", justifyContent: "center" }, title: { fontSize: 21, fontWeight: "800" }, subtitle: { fontSize: 12, marginTop: 3 }, online: { flexDirection: "row", gap: 5, alignItems: "center" }, onlineDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#588157" }, onlineText: { fontSize: 12, fontWeight: "800" }, messages: { padding: 18, paddingBottom: 25, flexGrow: 1 }, suggestions: { gap: 8, marginBottom: 18 }, chip: { alignSelf: "flex-start", borderWidth: 1, borderRadius: 20, paddingHorizontal: 13, paddingVertical: 10, minHeight: 40, justifyContent: "center" }, chipText: { fontSize: 12, fontWeight: "700" }, bubble: { maxWidth: "84%", borderRadius: 17, padding: 13, marginBottom: 11 }, userBubble: { alignSelf: "flex-end", borderBottomRightRadius: 5 }, aiBubble: { alignSelf: "flex-start", borderWidth: 1, borderBottomLeftRadius: 5 }, typing: { alignSelf: "flex-start", padding: 11, borderRadius: 15, flexDirection: "row", gap: 8, alignItems: "center" }, error: { fontSize: 12, marginTop: 4 }, composer: { paddingHorizontal: 15, paddingTop: 10, borderTopWidth: 1, flexDirection: "row", gap: 9, alignItems: "center" }, input: { flex: 1, minHeight: 48, maxHeight: 110, borderRadius: 15, paddingHorizontal: 14, borderWidth: 1, fontSize: 14 }, send: { width: 47, height: 47, borderRadius: 15, alignItems: "center", justifyContent: "center" } });