import { Ionicons } from "@expo/vector-icons";
import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useApp } from "@/src/context/AppContext";
import { useColors } from "@/src/components/common";

export default function HomeScreen({ onNavigate, onSettings }: { onNavigate: (screen: "scan" | "chat") => void; onSettings: () => void }) {
  const { t, user, updatePreferences } = useApp(); const c = useColors(); const insets = useSafeAreaInsets();
  const toggleTheme = () => void updatePreferences({ theme: user?.theme === "dark" ? "light" : "dark" });
  return <View style={[styles.root, { backgroundColor: c.bg }]}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 94 }]} showsVerticalScrollIndicator={false}>
    <View style={styles.top}><View><Text style={[styles.eyebrow, { color: c.muted }]}>{t.welcome},</Text><Text style={[styles.title, { color: c.text }]}>{user?.name || t.farmer}</Text></View><View style={styles.topActions}><Pressable testID="home-theme-toggle" accessibilityLabel={t.theme} onPress={toggleTheme} style={[styles.round, { backgroundColor: c.card }]}><Ionicons name={user?.theme === "dark" ? "sunny-outline" : "moon-outline"} size={20} color={c.text} /></Pressable><Pressable testID="home-settings" accessibilityLabel={t.settings} onPress={onSettings} style={[styles.avatar, { backgroundColor: c.brandSoft }]}><Ionicons name="settings-outline" size={20} color={c.brand} /></Pressable></View></View>
    <View style={[styles.weather, { backgroundColor: c.brand }]}><View><Text style={styles.weatherSmall}>PUNJAB • TODAY</Text><Text style={styles.weatherTemp}>28° <Text style={styles.weatherUnit}>C</Text></Text><Text style={styles.weatherText}>{t.fieldStatus}</Text></View><Ionicons name="partly-sunny-outline" size={58} color="#F7D6A8" /></View>
    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: c.text }]}>{t.myField}</Text><Text style={[styles.see, { color: c.brand }]}>{t.viewAll} ›</Text></View>
    <View style={[styles.fieldCard, { backgroundColor: c.card, borderColor: c.border }]}><View style={styles.fieldArt}><View style={[styles.fieldSun, { backgroundColor: "#D4A373" }]} /><View style={[styles.fieldRow, { backgroundColor: c.brandSoft }]} /><View style={[styles.fieldRow, { backgroundColor: c.brand, width: "78%" }]} /><View style={[styles.fieldRow, { backgroundColor: c.brandSoft, width: "62%" }]} /></View><View style={styles.fieldInfo}><Text style={[styles.fieldName, { color: c.text }]}>Green Valley field</Text><Text style={[styles.fieldMeta, { color: c.muted }]}>Wheat • 4.2 acres</Text><View style={styles.health}><View style={styles.healthDot} /><Text style={{ color: c.brand, fontWeight: "700", fontSize: 12 }}>{t.healthy} · 94%</Text></View></View></View>
    <Text style={[styles.sectionTitle, { color: c.text, marginTop: 26 }]}>{t.quickActions}</Text><View style={styles.grid}><Action testID="home-scan" icon="scan-outline" label={t.scanCrop} c={c} onPress={() => onNavigate("scan")} /><Action testID="home-chat" icon="chatbubble-ellipses-outline" label={t.askExpert} c={c} onPress={() => onNavigate("chat")} /><Action testID="home-weather" icon="cloud-outline" label={t.weather} c={c} /><Action testID="home-market" icon="trending-up-outline" label={t.market} c={c} /></View>
    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: c.text }]}>{t.recentHealth}</Text><Text style={[styles.see, { color: c.brand }]}>{t.viewAll} ›</Text></View><View style={[styles.update, { backgroundColor: c.card, borderColor: c.border }]}><View style={[styles.cropIcon, { backgroundColor: c.brandSoft }]}><Ionicons name="leaf-outline" size={24} color={c.brand} /></View><View style={{ flex: 1 }}><Text style={[styles.updateTitle, { color: c.text }]}>Wheat · North patch</Text><Text style={[styles.fieldMeta, { color: c.muted }]}>Scanned 2 days ago</Text></View><View style={styles.health}><View style={styles.healthDot} /><Text style={{ color: c.brand, fontSize: 12, fontWeight: "700" }}>{t.healthy}</Text></View></View>
    <View style={[styles.tip, { backgroundColor: c.cardAlt }]}><Ionicons name="bulb-outline" size={22} color={c.brand} /><View style={{ flex: 1 }}><Text style={[styles.tipLabel, { color: c.brand }]}>{t.fieldTip}</Text><Text style={[styles.tipText, { color: c.text }]}>{t.tip}</Text></View></View>
  </ScrollView></View>;
}
function Action({ testID, icon, label, c, onPress }: { testID: string; icon: keyof typeof Ionicons.glyphMap; label: string; c: ReturnType<typeof useColors>; onPress?: () => void }) { return <Pressable testID={testID} accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.action, { backgroundColor: c.card, borderColor: c.border }, pressed && { transform: [{ scale: .97 }] }]}><View style={[styles.actionIcon, { backgroundColor: c.brandSoft }]}><Ionicons name={icon} size={23} color={c.brand} /></View><Text style={[styles.actionText, { color: c.text }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingHorizontal: 18 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }, eyebrow: { fontSize: 13, marginBottom: 4 }, title: { fontSize: 27, fontWeight: "800" }, wave: { color: "#D4A373" }, topActions: { flexDirection: "row", gap: 9 }, round: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" }, avatar: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center" }, weather: { borderRadius: 20, padding: 20, minHeight: 134, flexDirection: "row", justifyContent: "space-between", alignItems: "center", overflow: "hidden" }, weatherSmall: { color: "#D5E2D4", fontSize: 11, fontWeight: "800", letterSpacing: 1 }, weatherTemp: { color: "#fff", fontSize: 36, fontWeight: "800", marginTop: 6 }, weatherUnit: { fontSize: 16, fontWeight: "500" }, weatherText: { color: "#E6F0E3", fontSize: 12, marginTop: 2 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 25, marginBottom: 12 }, sectionTitle: { fontSize: 19, fontWeight: "800" }, see: { fontSize: 12, fontWeight: "800" }, fieldCard: { borderWidth: 1, borderRadius: 18, padding: 12, flexDirection: "row", gap: 14 }, fieldArt: { width: 112, height: 103, backgroundColor: "#C2D5B9", borderRadius: 13, overflow: "hidden", justifyContent: "flex-end", alignItems: "center", paddingBottom: 15, gap: 5 }, fieldSun: { position: "absolute", width: 23, height: 23, borderRadius: 12, right: 11, top: 10 }, fieldRow: { height: 10, width: "88%", borderRadius: 6, transform: [{ rotate: "-8deg" }] }, fieldInfo: { flex: 1, justifyContent: "center" }, fieldName: { fontWeight: "800", fontSize: 15 }, fieldMeta: { fontSize: 12, marginTop: 5 }, health: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 12 }, healthDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#588157" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, action: { width: "48%", minHeight: 90, borderRadius: 16, padding: 13, borderWidth: 1 }, actionIcon: { width: 36, height: 36, borderRadius: 11, alignItems: "center", justifyContent: "center", marginBottom: 9 }, actionText: { fontWeight: "700", fontSize: 13 }, update: { borderWidth: 1, borderRadius: 16, padding: 13, flexDirection: "row", alignItems: "center", gap: 11 }, cropIcon: { width: 46, height: 46, borderRadius: 14, alignItems: "center", justifyContent: "center" }, updateTitle: { fontWeight: "800", fontSize: 14 }, tip: { marginTop: 13, padding: 15, borderRadius: 16, flexDirection: "row", gap: 11, alignItems: "flex-start" }, tipLabel: { fontSize: 12, fontWeight: "800", marginBottom: 4 }, tipText: { fontSize: 13, lineHeight: 19 }, });