import { Ionicons } from "@expo/vector-icons";
import * as ImagePicker from "expo-image-picker";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useApp } from "@/src/context/AppContext";
import { useColors } from "@/src/components/common";

type Form = { name: string; age: string; pincode: string; country: string; address: string };
export default function ProfileScreen({ onSettings }: { onSettings: () => void }) {
  const { t, user, updateProfile, logout } = useApp(); const c = useColors(); const insets = useSafeAreaInsets(); const [form, setForm] = useState<Form>({ name: "", age: "", pincode: "", country: "", address: "" }); const [photo, setPhoto] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { if (user) { setForm({ name: user.name || "", age: user.age || "", pincode: user.pincode || "", country: user.country || "India", address: user.address || "" }); setPhoto(user.photo || null); } }, [user]);
  const choosePhoto = async () => { const response = await ImagePicker.launchImageLibraryAsync({ base64: true, quality: .75, mediaTypes: ["images"] }); if (!response.canceled && response.assets[0]?.base64) { const mime = response.assets[0].mimeType || "image/jpeg"; const base = response.assets[0].base64; if (base) setPhoto(`data:${mime};base64,${base}`); } };
  const save = async () => { setBusy(true); setSaved(false); try { await updateProfile({ ...form, photo }); setSaved(true); } finally { setBusy(false); } };
  return <View style={[styles.root, { backgroundColor: c.bg }]}><ScrollView contentContainerStyle={[styles.content, { paddingTop: insets.top + 17, paddingBottom: insets.bottom + 95 }]}><View style={styles.top}><Text style={[styles.title, { color: c.text }]}>{t.profileTitle}</Text><Pressable testID="profile-settings" accessibilityLabel={t.settings} onPress={onSettings} style={[styles.settings, { backgroundColor: c.card }]}><Ionicons name="settings-outline" size={20} color={c.text} /></Pressable></View><View style={[styles.cover, { backgroundColor: c.brand }]}><View style={styles.coverLine} /><View style={styles.coverLine2} /></View><View style={styles.avatarWrap}><View style={[styles.avatar, { backgroundColor: c.brandSoft, borderColor: c.bg }]}>{photo ? <Image source={{ uri: photo }} style={styles.avatarImage} /> : <Ionicons name="person" size={42} color={c.brand} />}</View><Pressable testID="profile-photo" accessibilityLabel={t.photo} onPress={() => void choosePhoto()} style={[styles.camera, { backgroundColor: c.brand }]}><Ionicons name="camera" size={16} color="#fff" /></Pressable></View><Text style={[styles.photoLabel, { color: c.muted }]}>{t.photo}</Text><Text style={[styles.email, { color: c.text }]}>{user?.email}</Text>{user?.latitude != null && <View testID="profile-live-location" style={[styles.locationSaved, { backgroundColor: c.brandSoft }]}><Ionicons name="location" size={18} color={c.brand} /><View style={{ flex: 1 }}><Text style={[styles.locationSavedTitle, { color: c.brand }]}>{t.currentLocationSaved}</Text><Text testID="profile-location-label" style={[styles.locationSavedText, { color: c.text }]}>{[user.location_city, user.location_state].filter(Boolean).join(", ") || t.liveLocationActive}</Text></View></View>}<View style={styles.form}>{field(t.fullName, "name", form.name, setForm, c, "person-outline")}<View style={styles.two}>{field(t.age, "age", form.age, setForm, c, "calendar-outline")}<View style={{ width: 10 }} />{field(t.pincode, "pincode", form.pincode, setForm, c, "location-outline")}</View>{field(t.country, "country", form.country, setForm, c, "globe-outline")}{field(t.address, "address", form.address, setForm, c, "home-outline", true)}</View>{saved && <Text testID="profile-saved" style={[styles.saved, { color: c.brand }]}>{t.saved}</Text>}<Pressable testID="profile-save" onPress={() => void save()} disabled={busy} style={[styles.save, { backgroundColor: c.brand }, busy && { opacity: .65 }]}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>{t.save}</Text>}</Pressable><Pressable testID="profile-logout" onPress={() => void logout()} style={styles.logout}><Ionicons name="log-out-outline" size={19} color={c.danger} /><Text style={[styles.logoutText, { color: c.danger }]}>{t.logout}</Text></Pressable></ScrollView></View>;
}
function field(label: string, key: keyof Form, value: string, setForm: React.Dispatch<React.SetStateAction<Form>>, c: ReturnType<typeof useColors>, icon: keyof typeof Ionicons.glyphMap, multiline = false) { return <View style={[styles.field, { backgroundColor: c.card, borderColor: c.border }]}><Ionicons name={icon} size={18} color={c.muted} /><TextInput testID={`profile-${key}`} value={value} onChangeText={(next) => setForm((old) => ({ ...old, [key]: next }))} placeholder={label} placeholderTextColor={c.muted} multiline={multiline} style={[styles.fieldInput, { color: c.text }, multiline && { minHeight: 76, textAlignVertical: "top" }]} /></View>; }
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingHorizontal: 18 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }, title: { fontSize: 28, fontWeight: "800" }, settings: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, cover: { height: 91, borderRadius: 20, overflow: "hidden", position: "relative" }, coverLine: { position: "absolute", width: 220, height: 80, borderRadius: 90, borderWidth: 2, borderColor: "#759A77", right: -30, top: 27, transform: [{ rotate: "-12deg" }] }, coverLine2: { position: "absolute", width: 290, height: 90, borderRadius: 100, borderWidth: 2, borderColor: "#89A989", right: -70, top: 43, transform: [{ rotate: "-12deg" }] }, avatarWrap: { alignItems: "center", marginTop: -42 }, avatar: { width: 90, height: 90, borderRadius: 45, borderWidth: 5, alignItems: "center", justifyContent: "center", overflow: "hidden" }, avatarImage: { width: "100%", height: "100%" }, camera: { width: 31, height: 31, borderRadius: 16, alignItems: "center", justifyContent: "center", position: "absolute", right: "34%", bottom: -3, borderWidth: 3, borderColor: "#FDFBF7" }, photoLabel: { textAlign: "center", fontSize: 12, marginTop: 10 }, email: { textAlign: "center", fontSize: 13, marginTop: 4, marginBottom: 16 }, locationSaved: { borderRadius: 14, minHeight: 56, marginBottom: 14, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 10 }, locationSavedTitle: { fontSize: 12, fontWeight: "800" }, locationSavedText: { fontSize: 12, marginTop: 2 }, form: { gap: 11 }, field: { minHeight: 53, borderRadius: 14, borderWidth: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 14 }, fieldInput: { flex: 1, fontSize: 14, marginLeft: 10, minHeight: 51 }, two: { flexDirection: "row" }, saved: { textAlign: "center", fontWeight: "700", marginTop: 14 }, save: { minHeight: 53, borderRadius: 14, alignItems: "center", justifyContent: "center", marginTop: 14 }, saveText: { color: "#fff", fontWeight: "800", fontSize: 15 }, logout: { minHeight: 48, justifyContent: "center", alignItems: "center", flexDirection: "row", gap: 7, marginTop: 15 }, logoutText: { fontWeight: "800", fontSize: 14 } });